<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vofox-Sebastian" name="com.Home.Assessments" tests="16" failures="1" timestamp="24 Oct 2018 08:59:47 GMT" time="85.476" errors="0">
  <testcase name="TCED34201" time="11.989" classname="com.Home.Assessments">
    <failure type="java.lang.AssertionError" message="failed to assert text  Student Data Depot expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: failed to assert text  Student Data Depot expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.Home.Assessments.TCED34201(Assessments.java:52)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TCED34201 -->
  <testcase name="TCED34202" time="0.185" classname="com.Home.Assessments"/>
  <testcase name="TCED34203" time="0.915" classname="com.Home.Assessments"/>
  <testcase name="TCED34204" time="0.261" classname="com.Home.Assessments"/>
  <testcase name="TCED34205" time="11.293" classname="com.Home.Assessments"/>
  <testcase name="TCED34206" time="5.681" classname="com.Home.Assessments"/>
  <testcase name="TCED34207" time="0.416" classname="com.Home.Assessments"/>
  <testcase name="TCED34208" time="2.738" classname="com.Home.Assessments"/>
  <testcase name="TCED34209" time="11.304" classname="com.Home.Assessments"/>
  <testcase name="TCED34210" time="4.763" classname="com.Home.Assessments"/>
  <testcase name="TCED34211" time="1.203" classname="com.Home.Assessments"/>
  <testcase name="TCED34212" time="6.028" classname="com.Home.Assessments"/>
  <testcase name="TCED34213" time="11.333" classname="com.Home.Assessments"/>
  <testcase name="TCED34214" time="5.245" classname="com.Home.Assessments"/>
  <testcase name="TCED34215" time="0.385" classname="com.Home.Assessments"/>
  <testcase name="TCED34216" time="11.737" classname="com.Home.Assessments"/>
</testsuite> <!-- com.Home.Assessments -->
